apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ include "application.fullname" . }}-ngnix"
  namespace: {{ template "application.namespace" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  serviceName: "{{ template "application.fullname" . }}-ngnix"
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "application.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "application.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 30
      containers:
        - name: "{{ .Chart.Name }}"
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}  
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
              name: http
              protocol: TCP

