apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{.Values.frontend.name}}-build
  namespace: {{.Values.namespace}}
spec:
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2
  source:
    git:
      ref: {{.Values.frontend.git.branch}}
      uri: {{.Values.frontend.git.repository}}
    sourceSecret:
      name: "github-private-key"
    contextDir: {{.Values.frontend.git.contextDir}}
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: "DockerImage"
      name: {{.Values.frontend.image.repository}}:{{.Values.frontend.image.tag}}
    pushSecret:
      name: docker-push-pull-secret
  triggers:
    - type: ConfigChange
    - type: "GitHub"
      github:
        secret: "github-private-key"
  runPolicy: Serial