apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: site-bigbuckracing-com
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm
    repoURL: git@github.com:wgillaspy/site-bigbuckracing-com.git
    targetRevision: main
    helm:
      valueFiles: []
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
