# Default values for test-application.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: site-bigbuckracing-com

frontend:
  route:
    path: site-bigbuckracing-com.apps.local.hlokd.com
    enabled: true
  livenessProbeEnabled: false
  readinessProbeEnabled: false
  containerPort: 8080
  labels:
    app.kubernetes.io/instance: test-application-ngnix
    app.kubernetes.io/name: test-application-ngnix
  replicaCount: 1
  image:
    repository: "docker.io/williamgillaspy/hello-world"
    pullPolicy: Always
    tag: "latest"

service:
  type: ClusterIP
  port: 443 

imagePullSecrets:
  - name: docker-push-pull-secrets
